import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { doc, collection, setDoc, updateDoc, deleteDoc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=s=>document.querySelector(s);const rtcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]};let roomId=new URL(location.href).searchParams.get('room');let callRef=null,participantsUnsub=null,callUnsub=null,localStream=null;const peers=new Map(),candidateUnsubs=new Map();const name=()=>auth.currentUser?.displayName||auth.currentUser?.email?.split('@')[0]||'Developer';const color=()=>window.colorForUser?.(auth.currentUser?.uid)||'#7c83ff';const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const setRoom=()=>{roomId=new URL(location.href).searchParams.get('room')};
function ensurePanel(){if($('#callPanel'))return;document.body.insertAdjacentHTML('beforeend',`<div class="call-panel hidden" id="callPanel"><div class="call-head"><div><span class="eyebrow">LIVE COLLABORATION</span><h2>Team call</h2><p id="callStatus">Ready</p></div><button class="close" id="callClose">×</button></div><div class="video-grid" id="videoGrid"></div><div class="call-controls"><button class="call-control" id="muteCall">🎙️ Mute</button><button class="call-control" id="cameraCall">📷 Camera</button><button class="call-control" id="screenCall">▣ Share screen</button><button class="call-control end" id="endCall">End call</button></div></div>`);$('#callClose').onclick=()=>leaveCall();$('#endCall').onclick=()=>leaveCall();$('#muteCall').onclick=toggleMute;$('#cameraCall').onclick=toggleCamera;$('#screenCall').onclick=shareScreen}
function ensureButton(){const actions=document.querySelector('.room-actions');if(!actions||$('#startCall'))return;const b=document.createElement('button');b.className='ghost';b.id='startCall';b.textContent='Call';b.onclick=openCall;actions.insertBefore(b,actions.firstChild)}
function loadStyles(){if(document.querySelector('link[data-call-style]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./call.css';l.dataset.callStyle='1';document.head.appendChild(l)}
function addVideo(id,stream,label,local=false){let card=document.querySelector(`[data-video="${CSS.escape(id)}"]`);if(!card){card=document.createElement('div');card.className='video-card';card.dataset.video=id;card.innerHTML=`<video autoplay playsinline ${local?'muted':''}></video><span class="video-label"></span>`;$('#videoGrid').appendChild(card)}card.querySelector('video').srcObject=stream;card.querySelector('.video-label').innerHTML=`<i style="background:${local?color():'#8794ff'}"></i>${esc(label)}${local?' · You':''}`}
function removeVideo(id){document.querySelector(`[data-video="${CSS.escape(id)}"]`)?.remove()}function setStatus(t){if($('#callStatus'))$('#callStatus').textContent=t}
async function ensureMedia(){if(localStream)return localStream;if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera and microphone are not supported in this browser.');localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:true});addVideo(auth.currentUser.uid,localStream,name(),true);return localStream}
async function setupPeer(remote){if(!auth.currentUser||remote.uid===auth.currentUser.uid||peers.has(remote.uid))return;const me=auth.currentUser.uid,pairId=[me,remote.uid].sort().join('_'),pairRef=doc(db,'rooms',roomId,'calls','main','pairs',pairId),pc=new RTCPeerConnection(rtcConfig);peers.set(remote.uid,{pc,remote});localStream?.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.ontrack=e=>addVideo(remote.uid,e.streams[0],remote.name||'Developer');pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))removeVideo(remote.uid)};const side=me===pairId.split('_')[0]?'a':'b',other=side==='a'?'b':'a',mine=collection(pairRef,`${side}Candidates`);pc.onicecandidate=async e=>{if(e.candidate)await setDoc(doc(mine),{candidate:e.candidate.toJSON(),from:me,createdAt:serverTimestamp()})};const unsub=onSnapshot(pairRef,async snap=>{const d=snap.data()||{};try{if(side==='a'&&!d.offer){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await setDoc(pairRef,{a:me,b:remote.uid,offer:{type:offer.type,sdp:offer.sdp},updatedAt:serverTimestamp()},{merge:true})}if(side==='b'&&d.offer&&!pc.currentRemoteDescription){await pc.setRemoteDescription(d.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await setDoc(pairRef,{answer:{type:answer.type,sdp:answer.sdp},updatedAt:serverTimestamp()},{merge:true})}if(side==='a'&&d.answer&&!pc.currentRemoteDescription)await pc.setRemoteDescription(d.answer)}catch(e){setStatus('Connection issue — retrying…')}});const cu=onSnapshot(collection(pairRef,`${other}Candidates`),snap=>snap.docChanges().forEach(async ch=>{if(ch.type==='added'&&pc.remoteDescription)try{await pc.addIceCandidate(ch.doc.data().candidate)}catch(e){}}));candidateUnsubs.set(remote.uid,()=>{unsub();cu()})}
function closePeer(uid){const p=peers.get(uid);if(!p)return;p.pc.close();candidateUnsubs.get(uid)?.();candidateUnsubs.delete(uid);peers.delete(uid);removeVideo(uid)}
async function openCall(){setRoom();if(!roomId||!auth.currentUser)return;ensurePanel();$('#callPanel').classList.remove('hidden');try{await ensureMedia();callRef=doc(db,'rooms',roomId,'calls','main');await setDoc(callRef,{active:true,updatedAt:serverTimestamp(),startedBy:auth.currentUser.uid,startedByName:name()},{merge:true});await setDoc(doc(callRef,'participants',auth.currentUser.uid),{uid:auth.currentUser.uid,name:name(),color:color(),joinedAt:serverTimestamp(),online:true},{merge:true});callUnsub=onSnapshot(callRef,s=>{if(!s.exists()||!s.data().active)leaveCall(false)});participantsUnsub=onSnapshot(collection(callRef,'participants'),s=>{const list=s.docs.map(d=>d.data()).filter(p=>p.uid!==auth.currentUser.uid);setStatus(`${s.size} participant${s.size===1?'':'s'} connected`);list.forEach(setupPeer);for(const uid of [...peers.keys()])if(!list.some(p=>p.uid===uid))closePeer(uid)})}catch(e){setStatus(e.name==='NotAllowedError'?'Camera/microphone permission was denied.':`Call unavailable: ${e.message||e}`)}}
window.openCall=openCall;
async function leaveCall(mark=true){if(!auth.currentUser)return;for(const uid of [...peers.keys()])closePeer(uid);participantsUnsub?.();callUnsub?.();participantsUnsub=null;callUnsub=null;try{if(callRef){await deleteDoc(doc(callRef,'participants',auth.currentUser.uid));if(mark)await updateDoc(callRef,{active:false,updatedAt:serverTimestamp()})}}catch(e){}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}$('#videoGrid')?.replaceChildren();$('#callPanel')?.classList.add('hidden')}
function toggleMute(){const t=localStream?.getAudioTracks()[0];if(t){t.enabled=!t.enabled;$('#muteCall').textContent=t.enabled?'🎙️ Mute':'🔇 Unmute'}}function toggleCamera(){const t=localStream?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;$('#cameraCall').textContent=t.enabled?'📷 Camera':'🚫 Camera'}}
async function shareScreen(){if(!localStream)return;try{const screen=await navigator.mediaDevices.getDisplayMedia({video:true}),track=screen.getVideoTracks()[0];for(const {pc} of peers.values()){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(track)}const local=$(`[data-video="${CSS.escape(auth.currentUser.uid)}"] video`);if(local)local.srcObject=new MediaStream([track]);track.onended=()=>{const camera=localStream?.getVideoTracks()[0];for(const {pc} of peers.values()){const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender&&camera)sender.replaceTrack(camera)}if(local)local.srcObject=localStream}}catch(e){setStatus('Screen sharing was cancelled.')}}
function wire(){loadStyles();ensurePanel();ensureButton()}onAuthStateChanged(auth,()=>wire());wire();setInterval(()=>{setRoom();wire()},1000);
