import { auth, db } from './firebase.js';
import { collection, doc, onSnapshot, updateDoc, deleteDoc, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=s=>document.querySelector(s);let stop=null,roomId=null,files=[];
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function getRoom(){return new URL(location.href).searchParams.get('room')}
function ext(name){const m=name.toLowerCase().match(/\.([a-z0-9]+)$/);return m?m[1]:''}
function icon(name){const e=ext(name);return e==='js'||e==='mjs'?'JS':e==='ts'||e==='tsx'?'TS':e==='html'||e==='htm'?'HTML':e==='css'||e==='scss'?'CSS':e==='json'?'{}':e==='md'?'MD':e==='py'?'PY':e==='java'?'JAVA':e==='php'?'PHP':'FILE'}
function fileId(name){return files.find(f=>f.name===name)?.id}
function mount(){const panel=$('.files-panel');if(!panel||$('#fileTools'))return;panel.querySelector('.panel-title')?.insertAdjacentHTML('beforeend','<div class="file-tools" id="fileTools"><button type="button" id="newFolder" title="Create a folder and its first file">Folder</button><button type="button" id="renameFile">Rename</button><button type="button" id="duplicateFile">Duplicate</button><button type="button" id="deleteFile">Delete</button></div>');$('#newFolder').onclick=newFolder;$('#renameFile').onclick=renameSelected;$('#duplicateFile').onclick=duplicateSelected;$('#deleteFile').onclick=deleteSelected}
function selected(){const active=$('.file-item.active');return files.find(f=>f.id===active?.dataset.id)||null}
function renderTree(){const list=$('#fileList');if(!list)return;const original=[...list.querySelectorAll('.file-item')];if(!original.length)return;const activeId=original.find(b=>b.classList.contains('active'))?.dataset.id;const tree=document.createElement('div');tree.className='file-tree';const folders=new Map();for(const f of files){const parts=f.name.split('/');if(parts.length===1){const b=original.find(x=>x.dataset.id===f.id);if(b){b.querySelector('span')?.replaceChildren(document.createTextNode(icon(f.name)));b.querySelector('span')?.classList.add('language-icon');tree.appendChild(b)}}else{const folder=parts.slice(0,-1).join('/');if(!folders.has(folder)){const wrap=document.createElement('div');wrap.className='tree-folder';wrap.innerHTML=`<button class="folder-toggle" type="button"><span>▾</span><span>📁</span><strong>${esc(folder)}</strong></button><div class="folder-children"></div>`;tree.appendChild(wrap);folders.set(folder,wrap.querySelector('.folder-children'));const toggle=wrap.querySelector('.folder-toggle');toggle.onclick=()=>{wrap.classList.toggle('collapsed');toggle.querySelector('span').textContent=wrap.classList.contains('collapsed')?'▸':'▾'}}const b=original.find(x=>x.dataset.id===f.id);if(b){b.querySelector('span')?.replaceChildren(document.createTextNode(icon(parts.at(-1))));b.querySelector('span')?.classList.add('language-icon');b.textContent='';const badge=document.createElement('span');badge.className='language-icon';badge.textContent=icon(parts.at(-1));const label=document.createElement('span');label.textContent=parts.at(-1);b.append(badge,label);folders.get(folder).appendChild(b)}}}list.innerHTML='';list.appendChild(tree);if(activeId){const active=list.querySelector(`[data-id="${CSS.escape(activeId)}"]`);active?.classList.add('active')}}
async function newFolder(){if(!roomId||!auth.currentUser)return;const folder=prompt('Folder name, e.g. src');if(!folder)return;const safe=folder.trim().replace(/[^a-zA-Z0-9._-]/g,'');if(!safe)return alert('Use letters, numbers, dots, hyphens or underscores.');const name=prompt(`First file inside ${safe}/`,`${safe}/index.js`);if(!name)return;const clean=name.trim().replace(/[^a-zA-Z0-9._\/-]/g,'').replace(/^\/+|\/+$/g,'');if(!clean||!clean.startsWith(`${safe}/`))return alert(`The file must be inside ${safe}/`);if(files.some(f=>f.name===clean))return alert('That file already exists.');const language=ext(clean)==='css'?'css':ext(clean)==='html'?'html':'javascript';try{await addDoc(collection(db,'rooms',roomId,'files'),{name:clean,language,content:'',ownerId:auth.currentUser.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}catch(e){alert(`Could not create folder file: ${e.message||'Permission denied'}`)}}
async function renameSelected(){const f=selected();if(!roomId||!f)return alert('Select a file first.');const name=prompt('New file path',f.name);if(!name)return;const clean=name.trim().replace(/[^a-zA-Z0-9._\/-]/g,'').slice(0,160);if(!clean||clean===f.name)return;if(files.some(x=>x.name===clean))return alert('A file with that name already exists.');try{await updateDoc(doc(db,'rooms',roomId,'files',f.id),{name:clean,updatedAt:serverTimestamp()})}catch(e){alert(`Rename failed: ${e.message||'Permission denied'}`)}}
async function duplicateSelected(){const f=selected();if(!roomId||!f)return alert('Select a file first.');let base=f.name,candidate=base.replace(/(\.[^.]+)?$/, '-copy$1'),n=2;while(files.some(x=>x.name===candidate))candidate=base.replace(/(\.[^.]+)?$/, `-copy-${n++}$1`);try{await addDoc(collection(db,'rooms',roomId,'files'),{name:candidate,language:f.language||'javascript',content:f.content||'',ownerId:auth.currentUser.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}catch(e){alert(`Duplicate failed: ${e.message||'Permission denied'}`)}}
async function deleteSelected(){const f=selected();if(!roomId||!f)return alert('Select a file first.');if(files.length<=1)return alert('A project must keep at least one file.');if(!confirm(`Delete ${f.name}? This cannot be undone.`))return;try{await deleteDoc(doc(db,'rooms',roomId,'files',f.id))}catch(e){alert(`Delete failed: ${e.message||'Permission denied'}`)}}
function watch(){const next=getRoom();if(next===roomId)return;stop?.();roomId=next;files=[];if(!roomId||!auth.currentUser)return;stop=onSnapshot(collection(db,'rooms',roomId,'files'),s=>{files=s.docs.map(d=>({id:d.id,...d.data()}));mount();renderTree();updateLabels()})}
function updateLabels(){const f=selected();$('#renameFile')?.toggleAttribute('disabled',!f);$('#duplicateFile')?.toggleAttribute('disabled',!f);$('#deleteFile')?.toggleAttribute('disabled',!f||files.length<=1)}
let queued=false;function refresh(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;if(!$('#workspaceView')?.classList.contains('hidden')){mount();watch();renderTree();updateLabels()}})}
new MutationObserver(refresh).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});setInterval(refresh,1500);
