import { auth, db } from './firebase.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, updateProfile } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { collection, doc, setDoc, getDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';

const $=s=>document.querySelector(s);
let mode='signin';
const COLORS=['#7c83ff','#ff6b9d','#35c98b','#ffad4d','#5bbcff','#c084fc','#22d3ee','#f43f5e','#84cc16','#f59e0b','#14b8a6','#e879f9'];
const colorForUser=uid=>{let n=0;for(const ch of uid||'')n=(n*31+ch.charCodeAt(0))>>>0;return COLORS[n%COLORS.length]};
window.colorForUser=colorForUser;
function openAuth(next='signin'){mode=next;const signup=mode==='signup';$('#authTitle').textContent=signup?'Create your account':'Sign in';$('#authText').textContent=signup?'Create an account to start coding with your team.':'Sign in to create rooms and collaborate with your team.';$('#authAction').textContent=signup?'Create account':'Sign in';$('#authToggle').textContent=signup?'Already have an account? Sign in':'Need an account? Create one';$('#authMessage').textContent='';$('#authModal').classList.remove('hidden');$('#authEmail').focus()}
function authError(e){return ({'auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists with this email.','auth/weak-password':'Use a password with at least 6 characters.','auth/invalid-email':'Enter a valid email address.','auth/too-many-requests':'Too many attempts. Try again later.','auth/operation-not-allowed':'Enable Email/Password in Firebase Authentication.'})[e.code]||e.message||'Authentication failed.'}
async function createRoom(name){const clean=name.trim().replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,32);if(!clean)throw Error('Choose a valid room name.');const room=doc(collection(db,'rooms')),u=auth.currentUser,c=colorForUser(u.uid);await setDoc(room,{name:clean,ownerId:u.uid,language:'javascript',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await setDoc(doc(db,'rooms',room.id,'members',u.uid),{uid:u.uid,name:u.displayName||u.email?.split('@')[0]||'Developer',email:u.email,role:'owner',color:c,joinedAt:serverTimestamp(),lastSeen:serverTimestamp()});await setDoc(doc(db,'rooms',room.id,'files','main-js'),{name:'main.js',language:'javascript',content:'// Welcome to Coder Hub\n\nconsole.log("Hello, Coder Hub!");\n',ownerId:u.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});location.href=`./editor.html?room=${encodeURIComponent(room.id)}`}
async function joinRoom(id){const clean=id.trim();if(!clean)throw Error('Enter a room ID.');const snap=await getDoc(doc(db,'rooms',clean));if(!snap.exists())throw Error('Room not found. Check the room ID.');location.href=`./editor.html?room=${encodeURIComponent(clean)}`}
$('#createRoom')?.addEventListener('click',()=>auth.currentUser?openRoom('create'):openAuth('signin'));
$('#joinRoom')?.addEventListener('click',()=>auth.currentUser?openRoom('join'):openAuth('signin'));
function openRoom(kind){$('#modalTitle').textContent=kind==='create'?'Create a room':'Join a room';$('#modalText').textContent=kind==='create'?'Choose a room name to get started.':'Enter the room ID to join.';$('#roomName').placeholder=kind==='create'?'e.g. frontend-team':'Room ID';$('#modalAction').textContent=kind==='create'?'Create room':'Join room';$('#roomMessage').textContent='';$('#modal').classList.remove('hidden');$('#roomName').focus()}
$('#modalAction')?.addEventListener('click',async()=>{const b=$('#modalAction');b.disabled=true;try{if(b.textContent==='Create room')await createRoom($('#roomName').value);else await joinRoom($('#roomName').value)}catch(e){$('#roomMessage').textContent=e.message||'Could not continue.'}finally{b.disabled=false}});
$('#roomName')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#modalAction').click()});
$('#close')?.addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#authClose')?.addEventListener('click',()=>$('#authModal').classList.add('hidden'));$('#authToggle')?.addEventListener('click',()=>openAuth(mode==='signin'?'signup':'signin'));
$('#authForm')?.addEventListener('submit',async e=>{e.preventDefault();const b=$('#authAction');b.disabled=true;$('#authMessage').textContent='Working…';try{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(mode==='signup'){const c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:email.split('@')[0]})}else await signInWithEmailAndPassword(auth,email,password);$('#authModal').classList.add('hidden');e.target.reset()}catch(err){$('#authMessage').textContent=authError(err)}finally{b.disabled=false}});
$('#signin')?.addEventListener('click',()=>auth.currentUser?signOut(auth):openAuth('signin'));
onAuthStateChanged(auth,u=>{const b=$('#signin');if(b)b.textContent=u?'Sign out':'Sign in';const room=new URL(location.href).searchParams.get('room');if(u&&room)location.href=`./editor.html?room=${encodeURIComponent(room)}`});
