import { auth, db } from './firebase.js';
import { collection, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
let stop=null,files=[];const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function roomFromUrl(){return new URL(location.href).searchParams.get('room')}function pick(exts){return files.find(f=>exts.some(e=>f.name.toLowerCase().endsWith(e)))}
function buildDocument(){const html=pick(['.html','.htm']),css=pick(['.css']),js=pick(['.js','.mjs']);let body=html?.content||'<!doctype html><html><head><meta charset="utf-8"></head><body><h2>Live Preview</h2><p>Create an HTML file to preview your page.</p></body></html>';const style=css?.content||'',script=js?.content||'';const styleTag=`<style>${style.replace(/<\/style/gi,'<\\/style')}</style>`;if(/<head[\s>]/i.test(body))body=body.replace(/<\/head>/i,`${styleTag}</head>`);else body=`${styleTag}${body}`;if(script.trim())body=body.replace(/<\/body>/i,`<script>\n${script.replace(/<\/script/gi,'<\\/script')}\n<\/script></body>`);const bridge=`<script>(function(){function send(type,args){parent.postMessage({source:'coder-hub-preview',type,args:Array.from(args).map(v=>{try{return typeof v==='object'?JSON.stringify(v):String(v)}catch(e){return String(v)}})},'*')}['log','info','warn','error'].forEach(k=>{const old=console[k];console[k]=function(){send(k,arguments);old.apply(console,arguments)}});window.onerror=function(m,s,l){send('error',[m+' @ '+s+':'+l])};window.onunhandledrejection=function(e){send('error',['Unhandled promise rejection: '+(e.reason?.message||e.reason||'unknown')])}})();</script>`;return body.replace(/<head[\s>]/i,m=>m+bridge)}
function render(){const frame=$('#livePreview');if(!frame)return;const d=frame.contentDocument||frame.contentWindow.document;d.open();d.write(buildDocument());d.close();$('#previewStatus').textContent=`Preview updated · ${new Date().toLocaleTimeString()}`}
function renderInstant(name,content){const next=files.map(f=>f.name===name?{...f,content}:f);if(!next.some(f=>f.name===name))next.push({name,content});files=next;render()}
function addLog(type,args){const box=$('#previewConsole');if(!box)return;const row=document.createElement('div');row.className=`console-line console-${type}`;row.innerHTML=`<span class="console-type">${esc(type)}</span><span>${esc(args.join(' '))}</span>`;box.appendChild(row);box.scrollTop=box.scrollHeight}
function watch(){stop?.();const rid=roomFromUrl();if(!rid||!auth.currentUser)return;stop=onSnapshot(collection(db,'rooms',rid,'files'),s=>{files=s.docs.map(d=>({id:d.id,...d.data()}));render()},()=>{$('#previewStatus').textContent='Preview unavailable'})}
function mount(){if($('#previewStage'))return;const workspace=$('#workspaceView');if(!workspace)return;const grid=workspace.querySelector('.workspace-grid');if(!grid)return;const link=document.createElement('link');link.rel='stylesheet';link.href='./preview.css';document.head.appendChild(link);grid.insertAdjacentHTML('beforeend',`<section class="panel preview-stage" id="previewStage"><div class="panel-title"><span>Live Preview</span><div class="preview-controls"><span class="preview-status" id="previewStatus">Waiting for code…</span><select id="previewViewport" aria-label="Preview size"><option value="100%">Desktop</option><option value="768px">Tablet</option><option value="390px">Mobile</option></select><button id="refreshPreview" type="button">Refresh</button><button id="togglePreview" type="button">Collapse</button></div></div><div class="preview-frame-wrap" id="previewWrap"><iframe id="livePreview" title="Coder Hub live preview" sandbox="allow-scripts allow-forms"></iframe></div><div class="preview-console-head"><strong>Console</strong><button id="clearPreviewConsole" type="button">Clear</button></div><div class="preview-console" id="previewConsole" aria-live="polite"><div class="muted">Console output will appear here.</div></div></section>`);$('#refreshPreview').onclick=()=>{ $('#previewConsole').innerHTML='<div class="muted">Console output will appear here.</div>';render()};$('#clearPreviewConsole').onclick=()=>$('#previewConsole').innerHTML='<div class="muted">Console cleared.</div>';$('#togglePreview').onclick=()=>{const stage=$('#previewStage');stage.classList.toggle('collapsed');$('#togglePreview').textContent=stage.classList.contains('collapsed')?'Expand':'Collapse'};$('#previewViewport').onchange=e=>{const f=$('#livePreview');f.style.width=e.target.value;f.style.margin='0 auto'};watch()}
window.addEventListener('message',e=>{if(e.data?.source==='coder-hub-preview')addLog(e.data.type,e.data.args||[])});window.addEventListener('coderhub-editor-change',e=>{if(e.detail?.name)renderInstant(e.detail.name,e.detail.content||'')});
new MutationObserver(()=>{if(!$('#workspaceView')?.classList.contains('hidden')){mount();watch()}}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});setInterval(()=>{if(!$('#workspaceView')?.classList.contains('hidden'))watch()},1500);
